--Version:1.0.0.0
--Description:Initial Creation Script

-- UID mapping table
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UIDMapping](
	[ReleaseUID] [varchar](256) NOT NULL,
	[PrivateUID] [varchar](256) NOT NULL,
	[ProjectNumber] [int] NOT NULL,
	[UIDType] [int] NOT NULL,
 CONSTRAINT [PK_UIDMapping] PRIMARY KEY CLUSTERED
 (
	[ReleaseUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO